### ISSUE TITLE
Please dump diffs of the failed assertions

### ISSUE THREAD

**Issue by RReverser** [scottcorgan/tap-dot#13]
I really love dot reporter as it provides much less noise than the common ones, but on large test suites where all that you have is lots of comparisons, this is rather unhelpful:

<img width="1917" alt="screen shot 2016-05-06 at 9 51 26 am" src="https://cloud.githubusercontent.com/assets/557590/15068641/a6e3e632-1370-11e6-8bb5-125b9c9d7a63.png">

Could you please dump the diffs reported by tap instead of just messages?

**Comment by RReverser** [comment]
Actually from the screenshot in the README it appears they should be written out, but that doesn't seem to be the case as you can see in the screenshot above (using nothing special, just `t.deepEqual` here).

**Comment by scottcorgan** [comment]
Can you try https://www.npmjs.com/package/@tap-format/dot? It's the successor. Still haven't written any documentation, but it will get there.

**Comment by RReverser** [comment]
Tried, getting this after the dot lines:

```
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 4, column 9:
      actual:   ''
            ^
    at generateError (/Users/rreverser/Documents/Web/html5rl/js/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/rreverser/Documents/Web/html5rl/js/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readBlockMapping (/Users/rreverser/Documents/Web/html5rl/js/node_modules/js-yaml/lib/js-yaml/loader.js:1040:9)
    at composeNode (/Users/rreverser/Documents/Web/html5rl/js/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readDocument (/Users/rreverser/Documents/Web/html5rl/js/node_modules/js-yaml/lib/js-yaml/loader.js:1488:3)
    at loadDocuments (/Users/rreverser/Documents/Web/html5rl/js/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at load (/Users/rreverser/Documents/Web/html5rl/js/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at safeLoad (/Users/rreverser/Documents/Web/html5rl/js/node_modules/js-yaml/lib/js-yaml/loader.js:1579:10)
```
